version: 0.0
resources:
  - myK8sApp:
      type: AWS::EKS::Application
      properties:
        clusterName: kube_cluster
        namespace: default
        taskDefinition: k8s/deployment.yaml


