pipeline {
    agent {
        docker {
            image 'mridhuldoc/python-docker:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root:root'
        }
    }

    environment {
        DOCKERHUB_USERNAME = 'mridhuldoc'
        DOCKERHUB_REPO     = 'aws-continuous-integration-project'
        
        IMAGE_TAG          = "build-${BUILD_NUMBER}"   // unique tag per build
        APP_REPO           = 'https://github.com/mridul002/aws-continuous-integration-project.git'
        HELM_REPO          = 'https://github.com/mridhul002/python-helm-chart.git'
        APP_GIT_CRED       = 'github_pat'       // Jenkins credential ID for GitHub PAT
        HELM_GIT_CRED      = 'github_pat'       // same PAT works for Helm repo
    }

    stages {
       // stage('Checkout App Repo') {
         //   steps {
           //     git branch: 'dev',
             //       credentialsId: "${APP_GIT_CRED}",
               //     url: "${APP_REPO}"
          //  }
       // }

        stage('Install Dependencies & Run Tests') {
            steps {
                sh '''
                    pip install -r simple-python-app/requirements.txt
                    python -m unittest discover simple-python-app
                '''
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                sh 'rm -rf .venv'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                       docker build -t mridhuldoc/python-cal-project:latest -f simple-python-app/Dockerfile simple-python-app/
                       docker push mridhuldoc/python-cal-project:latest
                    '''
                }
            }
        }


        stage('Update Helm Chart Repo') {
            steps {
                sh """
                    # Clean up previous clone
                    rm -rf python-helm-chart
        
                    # Clone repo using SSH
                    git clone git@github.com:mridhul002/python-helm-chart.git
                    cd python-helm-chart
        
                    # Automatically create image tag
                    IMAGE_TAG="build-${BUILD_NUMBER}"
        
                    # Update values.yaml with new Docker image and tag
                    sed -i "s|repository:.*|repository: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO|" values.yaml
                    sed -i "s|tag:.*|tag: $IMAGE_TAG|" values.yaml
        
                    # Configure Git user
                    git config user.name "mridhul002"
                    git config user.email "mridhulofficial002@gmail.com"
        
                    # Commit changes if any
                    git add values.yaml
                    git commit -m "Update image to $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG" || echo "No changes to commit"
        
                    # Push back to GitHub
                    git push origin main
                """
            }
        }
    }
}




































