pipeline {
    agent {
        docker {
           image 'python:3.12-slim'
           args '-u root:root'
        }
    }

    environment {
        DOCKERHUB_USERNAME = 'mridhuldoc'
        DOCKERHUB_REPO     = 'aws-continuous-integration-project'
        
        IMAGE_TAG          = "build-${BUILD_NUMBER}"   // unique tag per build
        APP_REPO           = 'https://github.com/mridul002/aws-Continuous-integration-project.git'
        HELM_REPO          = 'https://github.com/mridul002/python-helm-chart.git'
        APP_GIT_CRED       = 'github-pat-mridul'       // Jenkins credential ID for GitHub PAT
        HELM_GIT_CRED      = 'github-pat-mridul'       // same PAT works for Helm repo
    }

    stages {
       // stage('Checkout App Repo') {
         //   steps {
           //     git branch: 'dev',
             //       credentialsId: "${APP_GIT_CRED}",
               //     url: "${APP_REPO}"
          //  }
       // }

        stage('Install Dependencies & Run Tests') {
            steps {
                sh '''
                    pip install -r simple-python-app/requirements.txt
                    python -m unittest discover simple-python-app
                '''
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                       sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
                       sudo docker build -t mridhuldoc/python-cal-project:latest .
                       sudo docker push mridhuldoc/python-cal-project:latest
                    '''
                }
            }
        }


        stage('Update Helm Chart Repo') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${HELM_GIT_CRED}", usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                    sh """
                        # clone helm chart repo
                        git clone https://$GIT_USER:$GIT_PASS@github.com/mridul002/python-helm-chart.git
                        cd python-helm-chart

                        # update values.yaml with new image + tag
                        sed -i "s|repository:.*|repository: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO|" values.yaml
                        sed -i "s|tag:.*|tag: $IMAGE_TAG|" values.yaml

                        git config user.name "mridul002"
                        git config user.email "mridhulofficial002@gmail.com"
                        git add values.yaml
                        git commit -m "Update image to $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG" || echo "No changes to commit"
                        git push origin main
                    """
                }
            }
        }
    }
}












