pipeline {
    agent {
        docker {
            image 'mridhuldoc/python-docker:latest'
            args '-v /var/run/docker.sock:/var/run/docker.sock -u root:root'
        }
    }

    environment {
        DOCKERHUB_USERNAME = 'mridhuldoc'
        DOCKERHUB_REPO     = 'aws-continuous-integration-project'
        
        IMAGE_TAG          = "build-${BUILD_NUMBER}"   // unique tag per build
        APP_REPO           = 'https://github.com/mridul002/aws-continuous-integration-project.git'
        HELM_REPO          = 'https://github.com/mridhul002/python-helm-chart.git'
        APP_GIT_CRED       = 'github-pat-mridul'       // Jenkins credential ID for GitHub PAT
        HELM_GIT_CRED      = 'github-pat-mridul'       // same PAT works for Helm repo
    }

    stages {
       // stage('Checkout App Repo') {
         //   steps {
           //     git branch: 'dev',
             //       credentialsId: "${APP_GIT_CRED}",
               //     url: "${APP_REPO}"
          //  }
       // }

        stage('Install Dependencies & Run Tests') {
            steps {
                sh '''
                    pip install -r simple-python-app/requirements.txt
                    python -m unittest discover simple-python-app
                '''
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                sh 'rm -rf .venv'
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                       echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                       docker build -t mridhuldoc/python-cal-project:latest -f simple-python-app/Dockerfile simple-python-app/
                       docker push mridhuldoc/python-cal-project:latest
                    '''
                }
            }
        }


        stage('Update Helm Chart Repo') {
            steps {
                withCredentials([string(credentialsId: 'github-pat-mridul', variable: 'GIT_TOKEN')]) {
                    sh """
                        # clone helm chart repo
                        git clone https://$GIT_TOKEN@github.com/mridul002/python-helm-chart.git
                        cd python-helm-chart

                        # update values.yaml with new image + tag
                        sed -i "s|repository:.*|repository: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO|" values.yaml
                        sed -i "s|tag:.*|tag: $IMAGE_TAG|" values.yaml

                        git config user.name "mridul002"
                        git config user.email "mridhulofficial002@gmail.com"
                        git add values.yaml
                        git commit -m "Update image to $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest" || echo "No changes to commit"
                        git push origin main
                    """
                }
            }
        }
    }
}

























